<?php 

function lastupdate_block_info(){

	$blocks = array();
	$blocks['date'] = array(
		'info' => t('Last date from update node'),
    	'cache' => DRUPAL_CACHE_PER_ROLE,
	);

	return $blocks;
}

function lastupdate_block_view($delta=''){
	switch($delta) {
		case 'date':
		
			return array(
				'subject' => 'Last modified date:',
				'content' => lastupdate_date_from_node(),
			);
	}
}

function lastupdate_date_from_node() {
    $last_updated = db_select('node', 'n')
            ->fields('n', array('changed'))
            ->condition('status', 0, '>') // only published nodes count
            ->orderBy('changed', 'DESC')
            ->range(0, 1)
            ->execute()
            ->fetchField();

    return format_date($last_updated);
}
?>